# __Hands-on with TensorFlow: Part A__

Let's see how TensorFlow works and build a deep neural network model using the MNIST dataset.

## Steps to be followed:
1. Import TensorFlow
2. Load the MNIST dataset
3. Create the model
4. Get predictions from the model
5. Apply softmax activation to the predictions
6. Define the loss function
7. Compile the model
8. Train the model
9. Evaluate the model
10. Create a probability model

## Step 1: Import TensorFlow

- Import TensorFlow and check its version.


In [ ]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.15.0


## Step 2: Load the MNIST dataset

- Load the MNIST dataset and normalize the input data by dividing the train and test sets by 255.



In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


__Observation:__
- The dataset has been downloaded.

## Step 3: Create the model

- Create a Sequential model with flatten, dense, and dropout layers.


In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

## Step 4: Get predictions from the model

- Get the predictions from the model using the train data for one column, as the optimizer is not yet applied.


In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.0162375 , -0.31711754, -0.69144183,  1.1094426 , -0.15561691,
        -0.44989958, -0.0533486 , -0.15329298, -0.3529281 , -0.47759974]],
      dtype=float32)

__Observation:__
- An array of predicted values is displayed.

## Step 5: Apply softmax activation to the predictions

- Apply softmax activation to the predictions and print the output in terms of probabilities.


In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.10265802, 0.07355609, 0.05058848, 0.30631328, 0.0864485 ,
        0.06440983, 0.09575732, 0.08664963, 0.07096861, 0.06265014]],
      dtype=float32)

__Observation:__
- The predicted values in terms of probabilities are displayed as an array.

## Step 6: Define the loss function

- Create a loss function for the model.
- Define the SparseCategoricalCrossentropy loss function.


In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

2.742489

__Observation:__
- Here, the value is 2.061.

## Step 7: Compile the model

- Compile the model with the Adam optimizer, the loss function, and the accuracy metric.

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

__Observation:__
- Here, we have used an optimizer as Adam, loss as a loss function, and metrics as accuracy.

## Step 8: Train the model

- Fit the model using the training data for 5 epochs.


In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 16s 7ms/step - loss: 0.2974 - accuracy: 0.9144
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1434 - accuracy: 0.9577
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1066 - accuracy: 0.9675
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0891 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0752 - accuracy: 0.9771


__Observations:__
- The model fits the data.
- Here, we can see that the accuracy is increased by different epochs.

## Step 9: Evaluate the model

- Evaluate the model using the testing data and print the results.


In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0705 - accuracy: 0.9791 - 622ms/epoch - 2ms/step


[0.07045573741197586, 0.9790999889373779]

__Observation:__

- The accuracy score is 0.9779, and the loss is 0.071.

## Step 10: Create a probability model

- Create a probability model by adding the softmax layer to the existing model.



In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

- Get the predictions using the test data

In [ ]:
probability_model(x_test[:3])

<tf.Tensor: shape=(3, 10), dtype=float32, numpy=
array([[2.35514889e-07, 2.79866819e-09, 3.38143991e-06, 2.87143248e-05,
        9.86441614e-13, 2.89823674e-07, 6.99302378e-13, 9.99965787e-01,
        3.53454510e-08, 1.63075674e-06],
       [1.58909774e-08, 1.07757633e-05, 9.99984145e-01, 2.48720539e-06,
        7.20975607e-14, 2.03693148e-07, 1.06905125e-08, 3.28412617e-13,
        2.41978705e-06, 9.13098915e-13],
       [1.75531738e-06, 9.98370707e-01, 1.04908802e-04, 1.69048635e-05,
        7.21752076e-05, 4.27044397e-05, 4.82732576e-05, 1.27938553e-03,
        6.06342146e-05, 2.55016516e-06]], dtype=float32)>

__Observation:__
- Here, we have the probabilities for the first three observations and different classes.